# The adapter to capture from.
source=wlan0

# Set the location for the db file. This must exist before Kismet starts.
log_prefix=/var/log/kismet

# Drop packets older than 24h so kismetdb doesn't grow unbounded.
kis_log_packet_timeout=86400
