name: Docker Example

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker container
        id: run-docker-container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/output.env:/output.env \
            alpine \
            /bin/sh -c "echo 'my_output=hello world' >> /output.env"
        
      - name: Load output as environment variable
        run: |
          source output.env
          echo "my_output is $my_output"

      - name: Use the output
        run: echo "$my_output"
